# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
    # # Run the linter
    -   id: ruff-check
        args: [--fix]
    # Run the formatter
    -   id: ruff-format
-   repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml", "-r"]
      additional_dependencies: ["bandit[toml]"]
# -   repo: local
#     hooks:
#     -   id: mypy
#         name: mypy type check
#         entry: poetry run mypy .
#         language: system
#         types: [python]
#         pass_filenames: false
#         args: [--config-file=pyproject.toml]
#         exclude: ^(scripts/|examples/|tests/)
#         require_serial: true
#         verbose: true
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: ./.venv_test/bin/pylint
#       # entry: env PYTHONPATH=. python -m pylint
#       language: python
#       types: [python]
#       args:
#         [
#           "--errors-only",
#           "-rn", # Only display messages
#           "-sn", # Don't display the score
#           "--rcfile=.pylintrc",
#         ]
#       additional_dependencies:
#         - pylint>=3.3.3
#         - sqlalchemy>=2.0.0
#         - alembic>=1.14.0
#         - rich>=13.7.0
#         - tqdm>=4.67.1
#         - stashapp-tools>=0.2.55
#         - pytest>=7.4.4
#         - aiosqlite>=0.20.0
#         - greenlet>=3.1.1
#         - imagehash>=4.2.0
#         - psutil>=5.8.0
#         - pyffmpeg>=0.2.0
#         - loguru>=0.5.3
#         - m3u8>=0.9.0
#         - pytest_asyncio>=0.15.1
#         - websockets>=12.0, <13.0
#         - strenum>=0.1.0
#         - toml>=0.10.2
#         - plyvel>=1.2.0
#         - pillow>=10.0.0
#         - python-dateutil>=2.8.2
#         - requests>=2.26.0
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.10.1'
#     hooks:
#     -   id: mypy
#         args: [--strict, --ignore-missing-imports, --no-incremental]
