coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 0%
    patch:
      default:
        target: 70%
        threshold: 0%

  ignore:
    - "*/venv/*"
    - "*/venv_test/*"
    - "*/__pycache__/*"
    - "*/tests/*"
    - "docs/*"
    - "*/migrations/*"
    - "*/.pytest_cache/*"
    - "*/.git/*"
    - "*/.github/*"
    - "*/htmlcov/*"
    - "stash/example.py"  # Example code, not production code

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  show_carryforward_flags: true
