[tool.poetry]
name = "fansly-scraper"
version = "0.10.0"
description = "Easy-to-use fansly.com content scraping tool. Enjoy your Fansly content offline anytime, anywhere in the highest possible content resolution! Fully customizable to download in bulk or single: photos, videos & audio from the timeline, messages, collection & single posts."
authors = [
    "prof79",
    "Avnsx",
    "pawnstar81",
    "UpAndDown666",
    "icewinterberry12",
    "1gintonic",
    "Jakan <github@jakan.co>",
]
# credits = [
#     "Avnsx",
#     "KasumiDev",
#     "FletcherD",
#     "XelaRellum",
#     "sunbart",
# ]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
imagehash = "4.3.1"
loguru = ">=0.7.2"
m3u8 = ">=4.0.0"
pillow = "^10.2"
plyvel-ci = "^1.5"
psutil = ">=5.9.8"
pyffmpeg = ">=2.4.2.18.1"
python-dateutil = ">=2.8.2,<3.0.0"
requests = ">=2.31.0,<3.0.0"
rich = ">=13.7.0,<14.0.0"
strenum = ">=0.4.15,<0.5.0"
websockets = ">=12.0,<13.0"
alembic = "^1.14.0"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.11.1"
types-python-dateutil = "^2.9.0.20241206"
types-requests = "^2.32.0.20241016"
types-setuptools = "^75.6.0.20241126"
types-pillow = "^10.2.0"
memory-profiler = "^0.61.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
