"""relationship_with_wall

Revision ID: 0b04c70972e4
Revises: 7c3779509867
Create Date: 2024-12-28 00:48:25.876570

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b04c70972e4"
down_revision: str | None = "7c3779509867"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys("account_media")

    with op.batch_alter_table("account_media") as batch_op:
        for constraint in constraints:
            if constraint["name"] == "fk_account_media_mediaId":
                batch_op.drop_constraint("fk_account_media_mediaId", type_="foreignkey")
                break
        batch_op.create_foreign_key(
            "fk_account_media_mediaId_cascade",
            "media",
            ["mediaId"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("media") as batch_op:
        batch_op.alter_column(
            "is_downloaded",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media") as batch_op:
        batch_op.alter_column(
            "is_downloaded",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    with op.batch_alter_table("account_media") as batch_op:
        batch_op.drop_constraint("fk_account_media_mediaId_cascade", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_account_media_mediaId",
            "media",
            ["mediaId"],
            ["id"],
        )
    # ### end Alembic commands ###
