"""index value of hashtag

Revision ID: 4416b99f028e
Revises: cc6fe4e9ef45
Create Date: 2025-01-08 15:25:26.573342

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4416b99f028e"
down_revision: str | None = "cc6fe4e9ef45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create index on hashtags.value
    with op.batch_alter_table("hashtags", schema=None) as batch_op:
        batch_op.create_index("ix_hashtags_value", ["value"], unique=True)

    # Add unique constraint to post_hashtags
    with op.batch_alter_table("post_hashtags", schema=None) as batch_op:
        batch_op.create_unique_constraint("pk_post_hashtags", ["postId", "hashtagId"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint from post_hashtags
    with op.batch_alter_table("post_hashtags", schema=None) as batch_op:
        batch_op.drop_constraint("pk_post_hashtags", type_="unique")

    # Remove index from hashtags.value
    with op.batch_alter_table("hashtags", schema=None) as batch_op:
        batch_op.drop_index("ix_hashtags_value")
    # ### end Alembic commands ###
