"""hashtags and stash_ids

Revision ID: cc6fe4e9ef45
Revises: 6dcb1d898d8b
Create Date: 2025-01-08 14:54:23.868946

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cc6fe4e9ef45"
down_revision: str | None = "6dcb1d898d8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create hashtags table with index on value for faster lookups
    op.create_table(
        "hashtags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("stash_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_hashtags"),
        sa.UniqueConstraint("value", name="uq_hashtags_value"),
    )

    # Create post_hashtags association table with indexes and named constraints
    op.create_table(
        "post_hashtags",
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("hashtagId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hashtagId"],
            ["hashtags.id"],
            name="fk_post_hashtags_hashtagId_hashtags",
            ondelete="CASCADE",  # If hashtag is deleted, remove associations
        ),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["posts.id"],
            name="fk_post_hashtags_postId_posts",
            ondelete="CASCADE",  # If post is deleted, remove associations
        ),
        sa.PrimaryKeyConstraint("postId", "hashtagId", name="pk_post_hashtags"),
    )

    # Create indexes for foreign keys
    op.create_index(
        "ix_post_hashtags_hashtagId", "post_hashtags", ["hashtagId"], unique=False
    )
    op.create_index(
        "ix_post_hashtags_postId", "post_hashtags", ["postId"], unique=False
    )
    op.add_column("account_media", sa.Column("stash_id", sa.Integer(), nullable=True))
    op.add_column(
        "account_media_bundles", sa.Column("stash_id", sa.Integer(), nullable=True)
    )
    op.add_column("media", sa.Column("stash_id", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("stash_id", sa.Integer(), nullable=True))
    op.add_column("posts", sa.Column("stash_id", sa.Integer(), nullable=True))
    op.add_column("walls", sa.Column("stash_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("walls", "stash_id")
    op.drop_column("posts", "stash_id")
    op.drop_column("messages", "stash_id")
    op.drop_column("media", "stash_id")
    op.drop_column("account_media_bundles", "stash_id")
    op.drop_column("account_media", "stash_id")

    # Drop indexes first
    op.drop_index("ix_post_hashtags_postId", table_name="post_hashtags")
    op.drop_index("ix_post_hashtags_hashtagId", table_name="post_hashtags")

    # Then drop tables (order matters due to foreign keys)
    op.drop_table("post_hashtags")
    op.drop_table("hashtags")
    # ### end Alembic commands ###
