"""adding stash_id to performer

Revision ID: f8df81787709
Revises: 0b04c70972e4
Create Date: 2025-01-07 02:24:16.213731

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8df81787709"
down_revision: str | None = "0b04c70972e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("stash_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "stash_id")
    # ### end Alembic commands ###
