"""Strawberry GraphQL types for Stash."""

# Base types
from .base import BulkUpdateIds, BulkUpdateStrings, StashObject

# Support types
from .config import (
    ConfigDefaultSettingsInput,
    ConfigDefaultSettingsResult,
    ConfigDisableDropdownCreate,
    ConfigDisableDropdownCreateInput,
    ConfigDLNAInput,
    ConfigDLNAResult,
    ConfigGeneralInput,
    ConfigGeneralResult,
    ConfigImageLightboxInput,
    ConfigImageLightboxResult,
    ConfigInterfaceInput,
    ConfigInterfaceResult,
    ConfigResult,
    Directory,
    GenerateAPIKeyInput,
    SetupInput,
    StashConfig,
    StashConfigInput,
)
from .enums import (
    BlobsStorageType,
    CircumisedEnum,
    CriterionModifier,
    FilterMode,
    GenderEnum,
    HashAlgorithm,
    ImageLightboxDisplayMode,
    ImageLightboxScrollMode,
    OnMultipleMatch,
    OrientationEnum,
    PackageType,
    PreviewPreset,
    ResolutionEnum,
    SortDirectionEnum,
    StreamingResolutionEnum,
)
from .files import (
    BaseFile,
    FileSetFingerprintsInput,
    Fingerprint,
    Folder,
    GalleryFile,
    ImageFile,
    MoveFilesInput,
    SetFingerprintsInput,
    StashID,
    VideoFile,
    VisualFile,
)
from .filters import (
    CircumcisionCriterionInput,
    CustomFieldCriterionInput,
    DateCriterionInput,
    DestroyFilterInput,
    FindFilterType,
    FloatCriterionInput,
    GalleryFilterType,
    GenderCriterionInput,
    GroupFilterType,
    HierarchicalMultiCriterionInput,
    ImageFilterType,
    IntCriterionInput,
    MultiCriterionInput,
    OrientationCriterionInput,
    PerformerFilterType,
    PhashDistanceCriterionInput,
    PHashDuplicationCriterionInput,
    ResolutionCriterionInput,
    SavedFilter,
    SavedFindFilterType,
    SaveFilterInput,
    SceneFilterType,
    SceneMarkerFilterType,
    SetDefaultFilterInput,
    StashIDCriterionInput,
    StringCriterionInput,
    StudioFilterType,
    TagFilterType,
    TimestampCriterionInput,
)

# Core types
from .gallery import (
    BulkGalleryUpdateInput,
    FindGalleriesResultType,
    FindGalleryChaptersResultType,
    Gallery,
    GalleryAddInput,
    GalleryChapter,
    GalleryChapterCreateInput,
    GalleryChapterUpdateInput,
    GalleryCreateInput,
    GalleryDestroyInput,
    GalleryPathsType,
    GalleryRemoveInput,
    GalleryResetCoverInput,
    GallerySetCoverInput,
    GalleryUpdateInput,
)
from .group import (
    BulkGroupUpdateInput,
    BulkUpdateGroupDescriptionsInput,
    FindGroupsResultType,
    Group,
    GroupCreateInput,
    GroupDescription,
    GroupDescriptionInput,
    GroupDestroyInput,
    GroupSubGroupAddInput,
    GroupSubGroupRemoveInput,
    GroupUpdateInput,
    ReorderSubGroupsInput,
)
from .image import (
    FindImagesResultType,
    Image,
    ImageDestroyInput,
    ImageFileType,
    ImagePathsType,
    ImagesDestroyInput,
)
from .job import FindJobInput, Job, JobStatus
from .logging import LogEntry, LogLevel
from .markers import (
    FindSceneMarkersResultType,
    MarkerStringsResultType,
    SceneMarker,
    SceneMarkerCreateInput,
    SceneMarkerTag,
    SceneMarkerUpdateInput,
)
from .metadata import (
    AnonymiseDatabaseInput,
    AutoTagMetadataInput,
    AutoTagMetadataOptions,
    BackupDatabaseInput,
    CleanGeneratedInput,
    CleanMetadataInput,
    CustomFieldsInput,
    ExportObjectsInput,
    ExportObjectTypeInput,
    GenerateMetadataInput,
    GenerateMetadataOptions,
    GeneratePreviewOptions,
    GeneratePreviewOptionsInput,
    IdentifyFieldOptions,
    IdentifyFieldOptionsInput,
    IdentifyMetadataOptions,
    IdentifyMetadataOptionsInput,
    ImportObjectsInput,
    MigrateInput,
    ScanMetaDataFilterInput,
    ScanMetadataInput,
    ScanMetadataOptions,
    SystemStatus,
)
from .not_implemented import (
    DLNAStatus,
    JobStatusUpdate,
    LatestVersion,
    SQLExecResult,
    SQLQueryResult,
    StashBoxValidationResult,
    Version,
)
from .performer import (
    FindPerformersResultType,
    Performer,
    PerformerCreateInput,
    PerformerUpdateInput,
)
from .scalars import Any, BoolMap, Int64, Map, PluginConfigMap, Time, Timestamp
from .scene import (
    AssignSceneFileInput,
    BulkSceneUpdateInput,
    FindScenesResultType,
    HistoryMutationResult,
    ParseSceneFilenameResult,
    ParseSceneFilenamesResult,
    Scene,
    SceneCreateInput,
    SceneDestroyInput,
    SceneFileType,
    SceneGroup,
    SceneGroupInput,
    SceneHashInput,
    SceneMergeInput,
    SceneMovieID,
    SceneMovieInput,
    SceneParserResult,
    SceneParserResultType,
    ScenePathsType,
    ScenesDestroyInput,
    SceneStreamEndpoint,
    SceneUpdateInput,
)
from .studio import (
    FindStudiosResultType,
    Studio,
    StudioCreateInput,
    StudioDestroyInput,
    StudioUpdateInput,
)
from .tag import (
    BulkTagUpdateInput,
    FindTagsResultType,
    Tag,
    TagCreateInput,
    TagDestroyInput,
    TagsMergeInput,
    TagUpdateInput,
)


__all__: list[str] = [  # noqa: RUF022 - Organized by semantic sections, not alphabetically
    # Base types
    "BulkUpdateIds",
    "BulkUpdateStrings",
    "StashObject",
    # Core types
    "Gallery",
    "Group",
    "Image",
    "Performer",
    "Scene",
    "Studio",
    "Tag",
    # Config types
    "ConfigDefaultSettingsInput",
    "ConfigDefaultSettingsResult",
    "ConfigDisableDropdownCreate",
    "ConfigDisableDropdownCreateInput",
    "ConfigDLNAInput",
    "ConfigDLNAResult",
    "ConfigGeneralInput",
    "ConfigGeneralResult",
    "ConfigImageLightboxInput",
    "ConfigImageLightboxResult",
    "ConfigInterfaceInput",
    "ConfigInterfaceResult",
    "ConfigResult",
    "Directory",
    "GenerateAPIKeyInput",
    "SetupInput",
    "StashConfig",
    "StashConfigInput",
    # File types
    "BaseFile",
    "FileSetFingerprintsInput",
    "Fingerprint",
    "Folder",
    "GalleryFile",
    "ImageFile",
    "MoveFilesInput",
    "SetFingerprintsInput",
    "StashID",
    "VideoFile",
    "VisualFile",
    # Filter types
    "CircumcisionCriterionInput",
    "CustomFieldCriterionInput",
    "DateCriterionInput",
    "DestroyFilterInput",
    "FindFilterType",
    "FloatCriterionInput",
    "GalleryFilterType",
    "GenderCriterionInput",
    "GroupFilterType",
    "HierarchicalMultiCriterionInput",
    "ImageFilterType",
    "IntCriterionInput",
    "MultiCriterionInput",
    "OrientationCriterionInput",
    "PerformerFilterType",
    "PhashDistanceCriterionInput",
    "PHashDuplicationCriterionInput",
    "ResolutionCriterionInput",
    "SavedFilter",
    "SavedFindFilterType",
    "SaveFilterInput",
    "SceneFilterType",
    "SceneMarkerFilterType",
    "SetDefaultFilterInput",
    "StashIDCriterionInput",
    "StringCriterionInput",
    "StudioFilterType",
    "TagFilterType",
    "TimestampCriterionInput",
    # Gallery types
    "BulkGalleryUpdateInput",
    "FindGalleriesResultType",
    "FindGalleryChaptersResultType",
    "GalleryAddInput",
    "GalleryChapter",
    "GalleryChapterCreateInput",
    "GalleryChapterUpdateInput",
    "GalleryCreateInput",
    "GalleryDestroyInput",
    "GalleryFile",
    "GalleryPathsType",
    "GalleryRemoveInput",
    "GalleryResetCoverInput",
    "GallerySetCoverInput",
    "GalleryUpdateInput",
    # Group types
    "BulkGroupUpdateInput",
    "BulkUpdateGroupDescriptionsInput",
    "FindGroupsResultType",
    "GroupCreateInput",
    "GroupDescription",
    "GroupDescriptionInput",
    "GroupDestroyInput",
    "GroupSubGroupAddInput",
    "GroupSubGroupRemoveInput",
    "GroupUpdateInput",
    "ReorderSubGroupsInput",
    # Image types
    "FindImagesResultType",
    "ImageDestroyInput",
    "ImageFileType",
    "ImagePathsType",
    "ImagesDestroyInput",
    # Job types
    "FindJobInput",
    "Job",
    "JobStatus",
    "JobStatusUpdate",
    # Log types
    "LogEntry",
    "LogLevel",
    # Marker types
    "FindSceneMarkersResultType",
    "MarkerStringsResultType",
    "SceneMarker",
    "SceneMarkerCreateInput",
    "SceneMarkerTag",
    "SceneMarkerUpdateInput",
    # Metadata types
    "AnonymiseDatabaseInput",
    "AutoTagMetadataInput",
    "AutoTagMetadataOptions",
    "BackupDatabaseInput",
    "CleanGeneratedInput",
    "CleanMetadataInput",
    "CustomFieldsInput",
    "ExportObjectsInput",
    "ExportObjectTypeInput",
    "GenerateMetadataInput",
    "GenerateMetadataOptions",
    "GeneratePreviewOptions",
    "GeneratePreviewOptionsInput",
    "IdentifyFieldOptions",
    "IdentifyFieldOptionsInput",
    "IdentifyMetadataOptions",
    "IdentifyMetadataOptionsInput",
    "ImportObjectsInput",
    "MigrateInput",
    "ScanMetaDataFilterInput",
    "ScanMetadataInput",
    "ScanMetadataOptions",
    "SystemStatus",
    # Performer types
    "FindPerformersResultType",
    "PerformerCreateInput",
    "PerformerUpdateInput",
    # Scene types
    "AssignSceneFileInput",
    "BulkSceneUpdateInput",
    "FindScenesResultType",
    "HistoryMutationResult",
    "ParseSceneFilenameResult",
    "ParseSceneFilenamesResult",
    "SceneCreateInput",
    "SceneDestroyInput",
    "SceneFileType",
    "SceneGroup",
    "SceneGroupInput",
    "SceneHashInput",
    "SceneMergeInput",
    "SceneMovieID",
    "SceneMovieInput",
    "SceneParserResult",
    "SceneParserResultType",
    "ScenePathsType",
    "ScenesDestroyInput",
    "SceneStreamEndpoint",
    "SceneUpdateInput",
    # Scalar types
    "Any",
    "BoolMap",
    "Int64",
    "Map",
    "PluginConfigMap",
    "Time",
    "Timestamp",
    # Studio types
    "FindStudiosResultType",
    "StudioCreateInput",
    "StudioDestroyInput",
    "StudioUpdateInput",
    # Tag types
    "BulkTagUpdateInput",
    "FindTagsResultType",
    "TagCreateInput",
    "TagDestroyInput",
    "TagsMergeInput",
    "TagUpdateInput",
    # Enum types
    "BlobsStorageType",
    "CircumisedEnum",
    "CriterionModifier",
    "FilterMode",
    "GenderEnum",
    "HashAlgorithm",
    "ImageLightboxDisplayMode",
    "ImageLightboxScrollMode",
    "OnMultipleMatch",
    "OrientationEnum",
    "PackageType",
    "PreviewPreset",
    "ResolutionEnum",
    "SortDirectionEnum",
    "StreamingResolutionEnum",
    # Not Implemented types
    "DLNAStatus",
    "JobStatusUpdate",
    "LatestVersion",
    "SQLExecResult",
    "SQLQueryResult",
    "StashBoxValidationResult",
    "Version",
]
